# Generated by Django 3.1.2 on 2020-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='榜单名称', max_length=30)),
                ('introduce', models.CharField(default='', help_text='榜单简介', max_length=500)),
                ('title_img', models.CharField(default='', help_text='榜单题图', max_length=50)),
                ('type', models.IntegerField(default=0, help_text='榜单类型, 客户端显示使用')),
                ('ct', models.IntegerField(default=0, help_text='创建时间')),
                ('ut', models.IntegerField(default=0, help_text='更新时间')),
            ],
            options={
                'db_table': 'tbl_board',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='游戏名称', max_length=50)),
                ('pinyin_name', models.CharField(default='', help_text='游戏拼音名', max_length=50)),
                ('pinyin_first', models.CharField(default='', help_text='游戏拼音首字母', max_length=50)),
                ('en_name', models.CharField(default='', help_text='游戏英文名', max_length=50)),
                ('other_name', models.CharField(default='', help_text='游戏别名', max_length=200)),
                ('title_img', models.CharField(default='', help_text='游戏题图', max_length=200)),
                ('icon', models.CharField(default='', help_text='游戏题图', max_length=200)),
                ('introduce', models.TextField(default='', help_text='游戏简介', max_length=200)),
                ('uid', models.IntegerField(default=0, help_text='用户id')),
                ('platform', models.CharField(default='', help_text='游戏平台 1=PC, 2=移动端, 3=XBOX, 4=PS, 5=NS', max_length=20)),
                ('state', models.IntegerField(default='', help_text='游戏题图')),
                ('create_time', models.IntegerField(default=0, help_text='创建时间')),
                ('update_time', models.IntegerField(default=0, help_text='更新时间')),
                ('wiki', models.CharField(default='', help_text='游戏wiki', max_length=200)),
                ('publish_date', models.IntegerField(default=0, help_text='发售日期')),
                ('other_info', models.CharField(default='', help_text='游戏其他信息', max_length=2000)),
                ('game_shot', models.CharField(default='', help_text='游戏截图', max_length=2000)),
                ('game_video', models.CharField(default='', help_text='游戏视频', max_length=2000)),
                ('review_count', models.IntegerField(default=0, help_text='游戏点评总数')),
                ('user_grade', models.IntegerField(default=0, help_text='用户总评分')),
                ('admin_grade', models.IntegerField(default=0, help_text='官方总评分')),
                ('user_grade_num', models.IntegerField(default=0, help_text='用户评分人数')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(default=0, help_text='游戏id')),
                ('bid', models.IntegerField(default=0, help_text='榜单id')),
                ('ct', models.IntegerField(default=0, help_text='创建时间')),
            ],
            options={
                'db_table': 'tbl_game_board',
            },
        ),
    ]
