# Generated by Django 3.1.2 on 2020-11-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('ct', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
